version: "3"

services:
  nginxproxy:
    depends_on:
      - nginx
    image: nginx:alpine
    container_name: proxyserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: always
    volumes:
      - ./myweb:/usr/share/nginx/html

  fastapi:
    build: ./LogParser
    restart: always
    container_name: logparser
    command: uvicorn main:app --host 0.0.0.0 --port 80